ALTER TABLE dupa_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE dupa_labor ENABLE ROW LEVEL SECURITY;
ALTER TABLE dupa_equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE dupa_materials ENABLE ROW LEVEL SECURITY;